kind: pipeline
type: docker
name: default

steps:
  - name: Build image
    image: plugins/docker
    settings:
      repo: stiforr/pyfa
      tags:
        - latest
        - build.${DRONE_BUILD_NUMBER}
      dry_run: true
      auto_tag: true

  - name: Release
    image: node
    commands:
      - yarn install
      - yarn semantic-release
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
