kind: pipeline
type: docker
name: default

steps:
  - name: Build image
    image: plugins/docker
    settings:
      repo: stiforr/pyfa
      tags:
        - latest
        - build.${DRONE_BUILD_NUMBER}
      dry_run: false
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  # - name: Shellcheck
  #   image: koalaman/shellcheck:stable
  #   commands:
  #     - shellcheck scripts/*

  # - name: Docker image size
  #   image: wagoodman/dive
  #   commands:
  #     - dive --highestUserWastedPercent "0.75" --lowestEfficiency "0.75" stiforr/pyfa:latest

  - name: Release
    image: node
    commands:
      - yarn install
      - yarn semantic-release
    environment:
      GH_TOKEN:
        from_secret: GH_TOKEN
    depends_on:
      - "Build image"
